### ISSUE TITLE
Too much foliage generation freezes the editor

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#11]
**Describe the bug**
If too much foliage is spawned, tasks don't go down much, UE freezes, no crash

**Affected release**
2.0p-317.1

**To Reproduce**
1. Create a Voxel Foliage Template with a very high range and moderate density (will provide exact numbers asap)
2. If Voxel Actor using this asset is in the scene

**Expected behavior**
Foliage tasks steadily go down, Foliage generates eventually

**Observed behavior**
Tasks get processed slightly, but then quickly get stuck, editor stutters and freezes indefinitely

**Comment by JarrodSeymour** [comment]
Issue 11 map in QA project is all set up to repro this. 

After waiting a bit, I did actually get an out-of-memory crash:

`Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\GenericPlatform\GenericPlatformMemory.cpp] [Line: 241] Ran out of memory allocating 694518928 bytes with alignment 8. Last error msg: The paging file is too small for this operation to complete..`

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
