### ISSUE TITLE
ensure raised in FVoxelTemplateNodeUtilities::GetDimension

### ISSUE THREAD

**Issue by Phyronnaz** [VoxelPlugin/issues#12]
**Describe the bug**
See repro

**Affected release**
dev-810

**To Reproduce**
1. Add a new WriteChannel node
2. Promote its Value pin to a Distance pin
3. Drag pin
4. Ensure

**Expected behavior**
No ensure

**Observed behavior**
Ensure

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
