### ISSUE TITLE
Foliage crash when using raytracing

### ISSUE THREAD

**Issue by Phyronnaz** [VoxelPlugin/issues#2]
**Describe the bug**
Foliage is crashing when raytracing is enabled.
![image](https://user-images.githubusercontent.com/16806877/236511386-a353c5bd-b009-40bc-be75-dbd71a0d390d.png)

**Affected release**
2.0p-317.1

**To Reproduce**
r.RayTracing=True in renderer settings
Open example map

**Expected behavior**
No crash

**Observed behavior**
Crash :)

**Comment by JarrodSeymour** [comment]
Tested in Landmass Foliage example and am getting this crash in dev 8089

Assertion failed: IsValid() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1109]

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
