### ISSUE TITLE
Clearing voxel scene with params gives error

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#20]
**Describe the bug**
When clearing a scene (with certain parameters) from a voxel actor, invalid parameter errors are thrown.
-In my case Vector2D parameter and Seed parameters were affected, the boolean and foliage asset parameters were not.)

**Affected release**
8135 debug

**To Reproduce**
1. Create a Voxel Actor
2. Create a Voxel Scene and assign it
3. Add Vector2D parameter and Seed parameter, set them to something. 
4. Change the value of these params on your Voxel Actor to something different
5. Now set your Voxel Actor's scene to none (clear it)

Note: Your Voxel scene graph might need to be fully setup, adding these params to one of the example graphs should work fine.

**Expected behavior**
No errors

**Observed behavior**
Voxel Scene graph errors are encountered (Invalid parameter Vector2D, invalid parameter Seed)

**Comment by Mr4Goosey** [comment]
This has since been refactored. Closed as this issue is unlikely to still be relevant.
