### ISSUE TITLE
VoxelParameterCollectionQueryData is required but not provided when using Expose Data node

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#26]
**Describe the bug**
Getting the Height through C++ works successfully without the WorldSeed parameter but as soon as I make a parameter out of it, the UVoxelGraphFunctionLibrary::QueryExposedVoxelData(...) throws the following errors:

```
PIE: Error: VS_Landscape.Graph :  WorldSeed : VoxelParameterCollectionQueryData is required but not provided by callee. Callstack:  WorldSeed  ->  Advanced Noise 2D  ->  Expose Data  Group: Synchronous
Voxel: Error: VS_Landscape.Graph :  WorldSeed : VoxelParameterCollectionQueryData is required but not provided by callee. Callstack:  WorldSeed  ->  Advanced Noise 2D  ->  Expose Data  Group: Synchronous
```

**Affected release**
Dev 8180

**To Reproduce**
1. Add an Expose Data node to your graph
2. Make a param out of it

**Expected behavior**
No errors

**Observed behavior**
Errors (included above) are encountered

**Comment by Mr4Goosey** [comment]
Closed as this node no longer exists
