### ISSUE TITLE
Banding when using Get Gradient

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#3]
**Describe the bug**
Utilizing the Get Gradient node produces banding artifacts.

**Affected release**
Repro on dev-7995

**To Reproduce**
1. Open Issue3 level and voxel scene
2. In preview scene, preview "Make Height Distance" pin
3. Note line-artifacts in large parts of the preview
4. In the level, move up while looking at terrain
5. Note holes appearing in the generally flat terrain despite distance checks being off in the scene

**Expected behavior**
A smooth, continuous gradient.

**Observed behavior**
A jagged, banded gradient with hard edges between cells.

**Comment by Mr4Goosey** [comment]
Might have managed to reproduce, but unsure if this is the same issue as initially reported.

**Comment by Phyronnaz** [comment]
This is an inherent limitation to how GetGradient works: we work on 2x2x2 cells, and these 8 values share their derivatives.

Fixing this would require adding another node that would force a gradient expansion when doing GetGradient
