### ISSUE TITLE
Crash when changing Voxel Size

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#4]
**Describe the bug**
The engine crashes without crash-log when changing the voxel size in a metagraph.

**Affected release**
2.0p-317

**To Reproduce**
1. ???
2. ???
3. Change voxel size on generate surface node

**Expected behavior**
The voxel scene should regenerate with the new voxel size

**Observed behavior**
The engine crashes without log

**Comment by Phyronnaz** [comment]
Try removing changing the scene on the scene actor while it's updating
