### ISSUE TITLE
CTRL+E and CTRL+B shortcuts not working for Voxel assets

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#44]
**Describe the bug**
Can't use Ctrl-E or Ctrl-B to Edit or Browse a Voxel Scene or Brush Asset

**Affected release**
Last release this was confirmed on, eg 2.0p-317Dev 8335

**To Reproduce**
1. Select  a Voxel Scene or Brush Asset in the viewport / Outliner
2. Press CTRL+B (to browse) and CTRL+E to edit

**Expected behavior**
CTRL+B should focus the asset in a Content Browser, CTRL+E should open the asset

**Observed behavior**
Nothing happens

**Comment by Mr4Goosey** [comment]
Still relevant, fairly small UX problem.
