### ISSUE TITLE
VoxelGraph Internal Pin Type error when using MakeVector node

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#50]
**Describe the bug**
Voxel graph throws an error when using make vector node, unless its output pin is disconnected

**Affected release**
dev 8419 debug

**To Reproduce**
1. Open voxel graph
2. create make vector node
3. Hook up the node to other nodes (write channel in this test)

**Expected behavior**
No error

**Observed behavior**
```
VoxelGraphErrors: Error: * : Internal error: Pin->Type == VoxelPin.GetType()
Voxel: Error: B_Continent.Graph  failed to compile
```

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
