### ISSUE TITLE
Voxel Actor not showing in SceneCaptureComponent's ShowOnly list

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#52]
**Describe the bug**
the VoxelSceneActor doesn't work with the "Use ShowOnly List" functionality of the SceneCaptureComponent2D

https://discord.com/channels/379297529235243020/1132832455506792558

**Affected release**
2.0p-317

**To Reproduce**
1. Add a Voxel Actor to the scene
2. Add a scene catpure component to an actor
3. Try to add Voxel Actor to Scene Capture Comp's ShowOnly list

**Expected behavior**
Actor is able to be added to array

**Observed behavior**
Actor doesn't sow up to be added

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
