### ISSUE TITLE
Crashing immediately when opening a graph instance

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#54]
**Describe the bug**
When opening a graph instance, engine crashes. Happens 100% of the time when using a heightmap.

**Affected release**
Dev-9077

**To Reproduce**
1. Create a graph
2. Create an instance of the graph
3. Add basic graph nodes (see included picture below), including a heightmap node
4. Crash

**Expected behavior**
No Crash

**Observed behavior**
Crash

![image](https://github.com/VoxelPlugin/issues/assets/98424334/1835af4b-5a83-4838-bb11-e07a9124cead)

**Comment by Mr4Goosey** [comment]
Closed as this issue is unlikely to still be relevant.
