### ISSUE TITLE
Macro graph - orphaned pins created when changing variable type

### ISSUE THREAD

**Issue by JarrodSeymour** [VoxelPlugin/issues#55]
**Describe the bug**
Reported by Scrappy:
https://discord.com/channels/379297529235243020/1013845644114403348/1141020629072629782

>  A small bug in the Macro graph (version 320.2p):
> 
> create a local variable. change its type. the variable node is broken.
> The workaround is to create a local variable only by dragging a pin out of the desired data type and then “Promote to local variable”

> Same happens when changing the data type of the new input/output. 
> So, every time I want to add a new input/output to the Macro Graph or make other changes, I have to unplug it in the Voxel Scene graph and delete it from there

**Affected release**
320.2p

**To Reproduce**
1. Make sure the Macro graph is in use in the Voxel Scene Graph
2. Make sure you are on the map where the graph executes
3. Add a new local variable
4. Result: errors and severe lags, increase of RAM usage

**Expected behavior**
No orphaned pins

**Observed behavior**
Orphaned pins

![image](https://github.com/VoxelPlugin/issues/assets/98424334/000ec995-d98e-416e-b043-c9c8272cd23e)

**Comment by Mr4Goosey** [comment]
This has since been refactored. Closed as this issue is unlikely to still be relevant.
