### ISSUE TITLE
Material Definition overwrites Channel within bounds

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#56]
**Describe the bug**
When a brush is used to write a material definition into a surface channel, that brush will override the materials of all other brushes within the chunks it affects.

**Affected release**
Confirmed on dev-9454

**To Reproduce**
1. Open Issue56
2. Note that only one brush (the lonely arch) has the orange material assigned, yet large parts of the surface display this material.

**Comment by Phyronnaz** [comment]
Fixed
