### ISSUE TITLE
Subtracting a Channel removes world 

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#57]
**Describe the bug**
If a surface channel is used to subtract from another surface, only chunks with brushes registered to that channel will still appear. The rest of the world will vanish.

**Affected release**
Confirmed on dev-9454

**To Reproduce**
1. Open Issue57
2. Note that only a tiny part of the world generates
3. Bypass the smooth subtract node; the world re-appears

**Comment by Phyronnaz** [comment]
Fixed
