### ISSUE TITLE
Multi-Query Channel returns non-array value

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#58]
**Describe the bug**
![image](https://github.com/VoxelPlugin/issues/assets/27518053/cb48970f-d86f-42fd-80ed-9bdae88b4fda)

**Affected release**
Confirmed on dev-9411.

**To Reproduce**
1. Open Issue58-59
2. Enter play mode
3. Note errors

**Comment by Phyronnaz** [comment]
Fixed
