### ISSUE TITLE
Query Channel returns 0

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#59]
**Describe the bug**
Using the Query Channel node in Blueprints will consistently return 0. 

**Affected release**
Confirmed on dev-9489.

**To Reproduce**

1. Open Issue58-59
2. Enter play mode
3. Note errors

**Comment by Phyronnaz** [comment]
Fixed https://github.com/VoxelPluginDev/VoxelPlugin/commit/55124da4b59324d9f46da834b240ea05dd95247c
