### ISSUE TITLE
Generate Foliage Crash

### ISSUE THREAD

**Issue by Mr4Goosey** [VoxelPlugin/issues#6]
**Describe the bug**
The engine crashses when placing a Generate Foliage node in a voxel scene.

**Affected release**
dev-7995

**To Reproduce**
1. Open 'Issue6_FoliageCrash'
2. Open the active voxel scene graph
3. Add a 'Generate Foliage' node
4. Crash

**Expected behavior**
No crash

**Observed behavior**
Crash

**Comment by JarrodSeymour** [comment]
Confirmed fixed in latest dev
